/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import static UI.INICIO.pnlmain;
import javax.swing.SwingWorker;
import logica.fconfiguration;

/**
 *
 * @author crist
 */
public class frmanalisis extends javax.swing.JInternalFrame {

    fconfiguration con = new fconfiguration();

    /**
     * Creates new form frmanalisis
     */
    public frmanalisis() {

        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btncomparacion.setToolTipText("<html><img src=\"" + frmanalisis.class.getResource("/img/comparacion.png") + "\">");
        btndistribucion.setToolTipText("<html><img src=\"" + frmanalisis.class.getResource("/img/distribucion.png") + "\">");
        btnevolutivo.setToolTipText("<html><img src=\"" + frmanalisis.class.getResource("/img/evolutivo.png") + "\">");
        btnfrecuencia.setToolTipText("<html><img src=\"" + frmanalisis.class.getResource("/img/frecuencia.png") + "\">");
        btnproyeccion.setToolTipText("<html><img src=\"" + frmanalisis.class.getResource("/img/proyeccion.png") + "\">");
        btnmaxmin.setToolTipText("<html><img src=\"" + frmanalisis.class.getResource("/img/mixmaxmin.png") + "\">");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btncomparacion = new javax.swing.JButton();
        btnevolutivo = new javax.swing.JButton();
        btnproyeccion = new javax.swing.JButton();
        btnfrecuencia = new javax.swing.JButton();
        btndistribucion = new javax.swing.JButton();
        btnmaxmin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btncomparacion.setBackground(new java.awt.Color(255, 255, 255));
        btncomparacion.setFont(new java.awt.Font("abeatbyKai", 0, 18)); // NOI18N
        btncomparacion.setForeground(new java.awt.Color(75, 16, 160));
        btncomparacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analisis.png"))); // NOI18N
        btncomparacion.setText("Distribucion KPI");
        btncomparacion.setToolTipText("Gráfica comparación KPI, valor objetivo frente a valor obtenido");
        btncomparacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncomparacion.setBorderPainted(false);
        btncomparacion.setFocusPainted(false);
        btncomparacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btncomparacion.setMaximumSize(new java.awt.Dimension(280, 54));
        btncomparacion.setMinimumSize(new java.awt.Dimension(280, 54));
        btncomparacion.setPreferredSize(new java.awt.Dimension(280, 54));
        btncomparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomparacionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPanel1.add(btncomparacion, gridBagConstraints);

        btnevolutivo.setBackground(new java.awt.Color(255, 255, 255));
        btnevolutivo.setFont(new java.awt.Font("abeatbyKai", 0, 18)); // NOI18N
        btnevolutivo.setForeground(new java.awt.Color(75, 16, 160));
        btnevolutivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analisis.png"))); // NOI18N
        btnevolutivo.setText("Evolutivo Mensual");
        btnevolutivo.setToolTipText("Gráfica evolutivo mensual");
        btnevolutivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnevolutivo.setBorderPainted(false);
        btnevolutivo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnevolutivo.setMaximumSize(new java.awt.Dimension(280, 54));
        btnevolutivo.setMinimumSize(new java.awt.Dimension(280, 54));
        btnevolutivo.setPreferredSize(new java.awt.Dimension(280, 54));
        btnevolutivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnevolutivoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPanel1.add(btnevolutivo, gridBagConstraints);

        btnproyeccion.setBackground(new java.awt.Color(255, 255, 255));
        btnproyeccion.setFont(new java.awt.Font("abeatbyKai", 0, 18)); // NOI18N
        btnproyeccion.setForeground(new java.awt.Color(75, 16, 160));
        btnproyeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analisis.png"))); // NOI18N
        btnproyeccion.setText("Stymuli Proyectado");
        btnproyeccion.setToolTipText("Gráfica proyección estímulo obtenido frente a estímulo posible");
        btnproyeccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnproyeccion.setBorderPainted(false);
        btnproyeccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnproyeccion.setMaximumSize(new java.awt.Dimension(280, 54));
        btnproyeccion.setMinimumSize(new java.awt.Dimension(280, 54));
        btnproyeccion.setPreferredSize(new java.awt.Dimension(280, 54));
        btnproyeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproyeccionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 7, 0, 0);
        jPanel1.add(btnproyeccion, gridBagConstraints);

        btnfrecuencia.setBackground(new java.awt.Color(255, 255, 255));
        btnfrecuencia.setFont(new java.awt.Font("abeatbyKai", 0, 18)); // NOI18N
        btnfrecuencia.setForeground(new java.awt.Color(75, 16, 160));
        btnfrecuencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analisis.png"))); // NOI18N
        btnfrecuencia.setText("Frecuencia Cumplimiento");
        btnfrecuencia.setToolTipText("Frecuencia de cumplimiento de módelos y KPI");
        btnfrecuencia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnfrecuencia.setBorderPainted(false);
        btnfrecuencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnfrecuencia.setMaximumSize(new java.awt.Dimension(280, 54));
        btnfrecuencia.setMinimumSize(new java.awt.Dimension(280, 54));
        btnfrecuencia.setPreferredSize(new java.awt.Dimension(280, 54));
        btnfrecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfrecuenciaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 0);
        jPanel1.add(btnfrecuencia, gridBagConstraints);

        btndistribucion.setBackground(new java.awt.Color(255, 255, 255));
        btndistribucion.setFont(new java.awt.Font("abeatbyKai", 0, 18)); // NOI18N
        btndistribucion.setForeground(new java.awt.Color(75, 16, 160));
        btndistribucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analisis.png"))); // NOI18N
        btndistribucion.setText("Distribucion Stymuli");
        btndistribucion.setToolTipText("Gráfica distribución del estímulo obtenido por cada Área");
        btndistribucion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btndistribucion.setBorderPainted(false);
        btndistribucion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btndistribucion.setMaximumSize(new java.awt.Dimension(280, 54));
        btndistribucion.setMinimumSize(new java.awt.Dimension(280, 54));
        btndistribucion.setPreferredSize(new java.awt.Dimension(280, 54));
        btndistribucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndistribucionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPanel1.add(btndistribucion, gridBagConstraints);

        btnmaxmin.setBackground(new java.awt.Color(255, 255, 255));
        btnmaxmin.setFont(new java.awt.Font("abeatbyKai", 0, 18)); // NOI18N
        btnmaxmin.setForeground(new java.awt.Color(75, 16, 160));
        btnmaxmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analisis.png"))); // NOI18N
        btnmaxmin.setText("Maximos y Minimos");
        btnmaxmin.setToolTipText("Máximo, Mínimo y media de valores obtenidos");
        btnmaxmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnmaxmin.setBorderPainted(false);
        btnmaxmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnmaxmin.setMaximumSize(new java.awt.Dimension(280, 54));
        btnmaxmin.setMinimumSize(new java.awt.Dimension(280, 54));
        btnmaxmin.setPreferredSize(new java.awt.Dimension(280, 54));
        btnmaxmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmaxminActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 9, 0, 0);
        jPanel1.add(btnmaxmin, gridBagConstraints);

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/isotipo-1-fondo-transparente91x77.png"))); // NOI18N
        jLabel2.setText("  ");
        jLabel2.setPreferredSize(new java.awt.Dimension(91, 85));
        jPanel2.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncomparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomparacionActionPerformed
        con.loadingscreen();
        SwingWorker swingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                INICIO.pnlmain.removeAll();
                INICIO.pnlmain.revalidate();
                INICIO.pnlmain.repaint();

                frmanalisdistrikpi form1chart = new frmanalisdistrikpi();

                if (INICIO.lblinicioacceso.getText().equals("Trabajador")) {

                } else if (INICIO.lblinicioacceso.getText().equals("Jefe de Area")) {

                    frmanalisdistrikpi.pnlarea.setVisible(false);
                    frmanalisdistrikpi.txtnombrearea.setText(INICIO.lblinicioarea.getText());

                } else if (INICIO.lblinicioacceso.getText().equals("Jefe de Subarea")) {

                    frmanalisdistrikpi.pnlarea.setVisible(false);
                    frmanalisdistrikpi.txtnombrearea.setText(INICIO.lblinicioarea.getText());

                }
                INICIO.pnlmain.add(form1chart);
                form1chart.toFront();
                form1chart.setVisible(true);
                form1chart.setSize(pnlmain.getSize());
                con.hideloading();
                return null;
            }
        };
        swingWorker.execute();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncomparacionActionPerformed

    private void btnevolutivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnevolutivoActionPerformed
        con.loadingscreen();
        SwingWorker swingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                INICIO.pnlmain.removeAll();
                INICIO.pnlmain.revalidate();
                INICIO.pnlmain.repaint();

                frmanalisevolutivo form3chart = new frmanalisevolutivo();

                if (INICIO.lblinicioacceso.getText().equals("Jefe de Area")) {
                    frmanalisevolutivo.pnlarea.setVisible(false);
                    frmanalisevolutivo.txtnombrearea.setText(INICIO.lblinicioarea.getText());

                } else if (INICIO.lblinicioacceso.getText().equals("Jefe de Subarea")) {
                    frmanalisevolutivo.pnlarea.setVisible(false);
                    frmanalisevolutivo.txtnombrearea.setText(INICIO.lblinicioarea.getText());

                }
                INICIO.pnlmain.add(form3chart);
                form3chart.toFront();
                form3chart.setVisible(true);
                form3chart.setSize(pnlmain.getSize());
                con.hideloading();
                return null;
            }
        };
        swingWorker.execute();
// TODO add your handling code here:
    }//GEN-LAST:event_btnevolutivoActionPerformed

    private void btnproyeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproyeccionActionPerformed
        con.loadingscreen();
        SwingWorker swingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                INICIO.pnlmain.removeAll();
                INICIO.pnlmain.revalidate();
                INICIO.pnlmain.repaint();

                frmanalisproyeccion form5chart = new frmanalisproyeccion();

                if (INICIO.lblinicioacceso.getText().equals("Jefe de Area")) {
                    frmanalisproyeccion.pnlarea.setVisible(false);
                    frmanalisproyeccion.txtnombrearea.setText(INICIO.lblinicioarea.getText());

                } else if (INICIO.lblinicioacceso.getText().equals("Jefe de Subarea")) {
                    frmanalisproyeccion.pnlarea.setVisible(false);
                    frmanalisproyeccion.txtnombrearea.setText(INICIO.lblinicioarea.getText());

                }
                INICIO.pnlmain.add(form5chart);
                form5chart.toFront();
                form5chart.setVisible(true);
                form5chart.setSize(pnlmain.getSize());
                con.hideloading();
                return null;
            }
        };
        swingWorker.execute();
// TODO add your handling code here:
    }//GEN-LAST:event_btnproyeccionActionPerformed

    private void btnfrecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfrecuenciaActionPerformed
        con.loadingscreen();
        SwingWorker swingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                INICIO.pnlmain.removeAll();
                INICIO.pnlmain.revalidate();
                INICIO.pnlmain.repaint();

                frmanalisfrecuencia form2chart = new frmanalisfrecuencia();

                if (INICIO.lblinicioacceso.getText().equals("Trabajador")) {

                } else if (INICIO.lblinicioacceso.getText().equals("Jefe de Area")) {
                    frmanalisfrecuencia.pnlarea.setVisible(false);
                    frmanalisfrecuencia.txtnombrearea.setText(INICIO.lblinicioarea.getText());

                } else if (INICIO.lblinicioacceso.getText().equals("Jefe de Subarea")) {
                    frmanalisfrecuencia.pnlarea.setVisible(false);
                    frmanalisfrecuencia.txtnombrearea.setText(INICIO.lblinicioarea.getText());

                }
                INICIO.pnlmain.add(form2chart);
                form2chart.toFront();
                form2chart.setVisible(true);
                form2chart.setSize(pnlmain.getSize());
                con.hideloading();
                return null;
            }
        };
        swingWorker.execute();
// TODO add your handling code here:
    }//GEN-LAST:event_btnfrecuenciaActionPerformed

    private void btndistribucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndistribucionActionPerformed
        con.loadingscreen();
        SwingWorker swingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                INICIO.pnlmain.removeAll();
                INICIO.pnlmain.revalidate();
                INICIO.pnlmain.repaint();

                frmanalisdistriestim form4chart = new frmanalisdistriestim();
                INICIO.pnlmain.add(form4chart);
                form4chart.toFront();
                form4chart.setVisible(true);
                form4chart.setSize(pnlmain.getSize());

                con.hideloading();
                return null;
            }
        };
        swingWorker.execute();// TODO add your handling code here:
    }//GEN-LAST:event_btndistribucionActionPerformed

    private void btnmaxminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmaxminActionPerformed
        con.loadingscreen();
        SwingWorker swingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                INICIO.pnlmain.removeAll();
                INICIO.pnlmain.revalidate();
                INICIO.pnlmain.repaint();

                frmanalisisminmaxmid form4chartkpi = new frmanalisisminmaxmid();

                if (INICIO.lblinicioacceso.getText().equals("Jefe de Area")) {
                    frmanalisisminmaxmid.pnlarea.setVisible(false);
                    frmanalisisminmaxmid.txtnombrearea.setText(INICIO.lblinicioarea.getText());

                } else if (INICIO.lblinicioacceso.getText().equals("Jefe de Subarea")) {
                    frmanalisisminmaxmid.pnlarea.setVisible(false);
                    frmanalisisminmaxmid.txtnombrearea.setText(INICIO.lblinicioarea.getText());

                }
                INICIO.pnlmain.add(form4chartkpi);
                form4chartkpi.toFront();
                form4chartkpi.setVisible(true);
                form4chartkpi.setSize(pnlmain.getSize());
                con.hideloading();
                return null;
            }
        };
        swingWorker.execute();
// TODO add your handling code here:
    }//GEN-LAST:event_btnmaxminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmanalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmanalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmanalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmanalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmanalisis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btncomparacion;
    public static javax.swing.JButton btndistribucion;
    public static javax.swing.JButton btnevolutivo;
    public static javax.swing.JButton btnfrecuencia;
    public static javax.swing.JButton btnmaxmin;
    public static javax.swing.JButton btnproyeccion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
