/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import static UI.INICIO.escritorio;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author crist
 */
public class frmanalisis extends javax.swing.JInternalFrame {

public static frmanalisdistrikpi form1chart;
public static frmanalisfrecuencia form2chart;
public static frmanalisevolutivo form3chart;
public static frmanalisdistriestim form4chart;
public static frmanalisproyeccion form5chart;

public static frmanalisischart6 form4chartkpi;
    /**
     * Creates new form frmanalisis
     */
    public frmanalisis() {

        initComponents();
       ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
btncomparacion.setToolTipText("<html><img src=\"" +frmanalisis.class.getResource("/img/comparacion.png")+"\">");
btndistribucion.setToolTipText("<html><img src=\"" +frmanalisis.class.getResource("/img/distribucion.png")+"\">");
btnevolutivo.setToolTipText("<html><img src=\"" +frmanalisis.class.getResource("/img/evolutivo.png")+"\">");
btnfrecuencia.setToolTipText("<html><img src=\"" +frmanalisis.class.getResource("/img/frecuencia.png")+"\">");
btnproyeccion.setToolTipText("<html><img src=\"" +frmanalisis.class.getResource("/img/proyeccion.png")+"\">");

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btncomparacion = new javax.swing.JButton();
        btnevolutivo = new javax.swing.JButton();
        btnproyeccion = new javax.swing.JButton();
        btnfrecuencia = new javax.swing.JButton();
        btndistribucion = new javax.swing.JButton();
        btnchart6 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(153, 103, 198));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btncomparacion.setBackground(new java.awt.Color(53, 29, 113));
        btncomparacion.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btncomparacion.setForeground(new java.awt.Color(255, 255, 255));
        btncomparacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analisis.png"))); // NOI18N
        btncomparacion.setText("Distribucion KPI");
        btncomparacion.setToolTipText("Gráfica comparación KPI, valor objetivo frente a valor obtenido");
        btncomparacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncomparacion.setBorderPainted(false);
        btncomparacion.setFocusPainted(false);
        btncomparacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btncomparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomparacionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 64;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 0, 0);
        jPanel1.add(btncomparacion, gridBagConstraints);

        btnevolutivo.setBackground(new java.awt.Color(53, 29, 113));
        btnevolutivo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnevolutivo.setForeground(new java.awt.Color(255, 255, 255));
        btnevolutivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analisis.png"))); // NOI18N
        btnevolutivo.setText("Evolutivo Mensual");
        btnevolutivo.setToolTipText("Gráfica evolutivo mensual");
        btnevolutivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnevolutivo.setBorderPainted(false);
        btnevolutivo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnevolutivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnevolutivoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPanel1.add(btnevolutivo, gridBagConstraints);

        btnproyeccion.setBackground(new java.awt.Color(53, 29, 113));
        btnproyeccion.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnproyeccion.setForeground(new java.awt.Color(255, 255, 255));
        btnproyeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analisis.png"))); // NOI18N
        btnproyeccion.setText("Stymuli Proyectado");
        btnproyeccion.setToolTipText("Gráfica proyección estímulo obtenido frente a estímulo posible");
        btnproyeccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnproyeccion.setBorderPainted(false);
        btnproyeccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnproyeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproyeccionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 10);
        jPanel1.add(btnproyeccion, gridBagConstraints);

        btnfrecuencia.setBackground(new java.awt.Color(53, 29, 113));
        btnfrecuencia.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnfrecuencia.setForeground(new java.awt.Color(255, 255, 255));
        btnfrecuencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analisis.png"))); // NOI18N
        btnfrecuencia.setText("Frecuencia Cumplimiento");
        btnfrecuencia.setToolTipText("Frecuencia de cumplimiento de módelos y KPI");
        btnfrecuencia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnfrecuencia.setBorderPainted(false);
        btnfrecuencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnfrecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfrecuenciaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 0, 10);
        jPanel1.add(btnfrecuencia, gridBagConstraints);

        btndistribucion.setBackground(new java.awt.Color(53, 29, 113));
        btndistribucion.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btndistribucion.setForeground(new java.awt.Color(255, 255, 255));
        btndistribucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analisis.png"))); // NOI18N
        btndistribucion.setText("Distribucion Stymuli");
        btndistribucion.setToolTipText("Gráfica distribución del estímulo obtenido por cada Área");
        btndistribucion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btndistribucion.setBorderPainted(false);
        btndistribucion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btndistribucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndistribucionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        jPanel1.add(btndistribucion, gridBagConstraints);

        btnchart6.setBackground(new java.awt.Color(53, 29, 113));
        btnchart6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnchart6.setForeground(new java.awt.Color(255, 255, 255));
        btnchart6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analisis.png"))); // NOI18N
        btnchart6.setText("Distribucion Stymuli KPI");
        btnchart6.setToolTipText("Análisis Histórico");
        btnchart6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnchart6.setBorderPainted(false);
        btnchart6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnchart6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchart6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 6, 0, 10);
        jPanel1.add(btnchart6, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncomparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomparacionActionPerformed


        
if(form1chart!=null){
           form1chart.dispose();
       }
if(form2chart!=null){
           form2chart.dispose();
       }
if(form3chart!=null){
           form3chart.dispose();
       }
if(form4chart!=null){
           form4chart.dispose();
       }
if(form5chart!=null){
           form5chart.dispose();
       }

if(form4chartkpi!=null){
           form4chartkpi.dispose();
       }





      form1chart=new frmanalisdistrikpi();
       escritorio.add(form1chart);
       form1chart.toFront();
       form1chart.setVisible(true);
       Dimension desktopSize = escritorio.getSize();
Dimension jInternalFrameSize = form1chart.getSize();
form1chart.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);

        if (INICIO.lblinicioacceso.getText().equals("Trabajador")) {
            
          
        } else if (INICIO.lblinicioacceso.getText().equals("Jefe de Area")) {
            
            frmanalisdistrikpi.pnlarea.setVisible(false);
            frmanalisdistrikpi.txtnombrearea.setText(INICIO.lblinicioarea.getText());
     
        } else if (INICIO.lblinicioacceso.getText().equals("Jefe de Subarea")) {
            
            frmanalisdistrikpi.pnlarea.setVisible(false);
            frmanalisdistrikpi.txtnombrearea.setText(INICIO.lblinicioarea.getText());
        

        } 

  

        // TODO add your handling code here:
    }//GEN-LAST:event_btncomparacionActionPerformed

    private void btnevolutivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnevolutivoActionPerformed

      
        
if(form1chart!=null){
           form1chart.dispose();
       }
if(form2chart!=null){
           form2chart.dispose();
       }
if(form3chart!=null){
           form3chart.dispose();
       }
if(form4chart!=null){
           form4chart.dispose();
       }
if(form5chart!=null){
           form5chart.dispose();
       }

if(form4chartkpi!=null){
           form4chartkpi.dispose();
       }

      form3chart=new frmanalisevolutivo();
       escritorio.add(form3chart);
       form3chart.toFront();
       form3chart.setVisible(true);
       Dimension desktopSize = escritorio.getSize();
Dimension jInternalFrameSize = form3chart.getSize();
form3chart.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);      
   
            
          
        if (INICIO.lblinicioacceso.getText().equals("Trabajador")) {
            
          
        } else if (INICIO.lblinicioacceso.getText().equals("Jefe de Area")) {
            frmanalisevolutivo.pnlarea.setVisible(false);
            frmanalisevolutivo.txtnombrearea.setText(INICIO.lblinicioarea.getText());
     
        } else if (INICIO.lblinicioacceso.getText().equals("Jefe de Subarea")) {
            frmanalisevolutivo.pnlarea.setVisible(false);
            frmanalisevolutivo.txtnombrearea.setText(INICIO.lblinicioarea.getText());
        

        } 


// TODO add your handling code here:
    }//GEN-LAST:event_btnevolutivoActionPerformed

    private void btnproyeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproyeccionActionPerformed

     
        
if(form1chart!=null){
           form1chart.dispose();
       }
if(form2chart!=null){
           form2chart.dispose();
       }
if(form3chart!=null){
           form3chart.dispose();
       }
if(form4chart!=null){
           form4chart.dispose();
       }
if(form5chart!=null){
           form5chart.dispose();
       }

if(form4chartkpi!=null){
           form4chartkpi.dispose();
       }

      form5chart=new frmanalisproyeccion();
       escritorio.add(form5chart);
       form5chart.toFront();
       form5chart.setVisible(true);
       Dimension desktopSize = escritorio.getSize();
Dimension jInternalFrameSize = form5chart.getSize();
form5chart.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);    

   if (INICIO.lblinicioacceso.getText().equals("Trabajador")) {
            
          
        } else if (INICIO.lblinicioacceso.getText().equals("Jefe de Area")) {
            frmanalisproyeccion.pnlarea.setVisible(false);
            frmanalisproyeccion.txtnombrearea.setText(INICIO.lblinicioarea.getText());
     
        } else if (INICIO.lblinicioacceso.getText().equals("Jefe de Subarea")) {
            frmanalisproyeccion.pnlarea.setVisible(false);
            frmanalisproyeccion.txtnombrearea.setText(INICIO.lblinicioarea.getText());
        

        } 


// TODO add your handling code here:
    }//GEN-LAST:event_btnproyeccionActionPerformed

    private void btnfrecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfrecuenciaActionPerformed


if(form1chart!=null){
           form1chart.dispose();
       }
if(form2chart!=null){
           form2chart.dispose();
       }
if(form3chart!=null){
           form3chart.dispose();
       }
if(form4chart!=null){
           form4chart.dispose();
       }
if(form5chart!=null){
           form5chart.dispose();
       }

if(form4chartkpi!=null){
           form4chartkpi.dispose();
       }

      form2chart=new frmanalisfrecuencia();
       escritorio.add(form2chart);
       form2chart.toFront();
       form2chart.setVisible(true);
       Dimension desktopSize = escritorio.getSize();
Dimension jInternalFrameSize = form2chart.getSize();
form2chart.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);  

  if (INICIO.lblinicioacceso.getText().equals("Trabajador")) {
            
          
        } else if (INICIO.lblinicioacceso.getText().equals("Jefe de Area")) {
              frmanalisfrecuencia.pnlarea.setVisible(false);
            frmanalisfrecuencia.txtnombrearea.setText(INICIO.lblinicioarea.getText());
        
     
        } else if (INICIO.lblinicioacceso.getText().equals("Jefe de Subarea")) {
              frmanalisfrecuencia.pnlarea.setVisible(false);
            frmanalisfrecuencia.txtnombrearea.setText(INICIO.lblinicioarea.getText());
        
        

        } 


// TODO add your handling code here:
    }//GEN-LAST:event_btnfrecuenciaActionPerformed

    private void btndistribucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndistribucionActionPerformed


if(form1chart!=null){
           form1chart.dispose();
       }
if(form2chart!=null){
           form2chart.dispose();
       }
if(form3chart!=null){
           form3chart.dispose();
       }
if(form4chart!=null){
           form4chart.dispose();
       }
if(form4chartkpi!=null){
           form4chartkpi.dispose();
       }

if(form5chart!=null){
           form5chart.dispose();
       }

      form4chart=new frmanalisdistriestim();
       escritorio.add(form4chart);
       form4chart.toFront();
       form4chart.setVisible(true);
       Dimension desktopSize = escritorio.getSize();
Dimension jInternalFrameSize = form4chart.getSize();
form4chart.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);        // TODO add your handling code here:
    }//GEN-LAST:event_btndistribucionActionPerformed

    private void btnchart6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchart6ActionPerformed
     
        
if(form1chart!=null){
           form1chart.dispose();
       }
if(form2chart!=null){
           form2chart.dispose();
       }
if(form3chart!=null){
           form3chart.dispose();
       }
if(form4chart!=null){
           form4chart.dispose();
       }
if(form4chartkpi!=null){
           form4chartkpi.dispose();
       }
if(form5chart!=null){
           form5chart.dispose();
       }

      form4chartkpi=new frmanalisischart6();
       escritorio.add(form4chartkpi);
       form4chartkpi.toFront();
       form4chartkpi.setVisible(true);
       Dimension desktopSize = escritorio.getSize();
Dimension jInternalFrameSize = form4chartkpi.getSize();
form4chartkpi.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
    (desktopSize.height- jInternalFrameSize.height)/2);        // TODO add your handling code here:
    }//GEN-LAST:event_btnchart6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmanalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmanalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmanalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmanalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmanalisis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnchart6;
    public static javax.swing.JButton btncomparacion;
    public static javax.swing.JButton btndistribucion;
    public static javax.swing.JButton btnevolutivo;
    public static javax.swing.JButton btnfrecuencia;
    public static javax.swing.JButton btnproyeccion;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
