/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import datos.vresultados;

import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import logica.conexion;
import logica.fconfiguration;
import logica.fresultados;
import logica.fsqloperations;

/**
 *
 * @author crist
 */
public class frmresultados extends javax.swing.JInternalFrame {

    fconfiguration con = new fconfiguration();
    /**
     * Creates new form frmtrabajador
     */
    String filtropor = "p.documento";

    public frmresultados() {

        initComponents();
        mostrar("", filtropor);
        inhabilitar();
        conexion.frmabierto = 4;
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tablalistado.setDefaultEditor(Object.class, null);
        tablalistado.setShowGrid(true);
        jScrollPane1.getViewport().setBackground(new Color(101, 54, 193));

        btncomparacion.setToolTipText("<html><img src=\"" + frmanalisis.class.getResource("/img/comparacion.png") + "\">");
        btnevolutivo.setToolTipText("<html><img src=\"" + frmanalisis.class.getResource("/img/evolutivo.png") + "\">");
        btnproyeccion.setToolTipText("<html><img src=\"" + frmanalisis.class.getResource("/img/proyeccion.png") + "\">");

        Action buscar = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnbuscar.doClick();
            }
        };
        txtbuscar.addActionListener(buscar);

    }
    private String accion = "guardar";

    void ocultar_columnas() {
        tablalistado.getColumnModel().getColumn(0).setMaxWidth(0);
        tablalistado.getColumnModel().getColumn(0).setMinWidth(0);
        tablalistado.getColumnModel().getColumn(0).setPreferredWidth(0);

        tablalistado.getColumnModel().getColumn(1).setMaxWidth(0);
        tablalistado.getColumnModel().getColumn(1).setMinWidth(0);
        tablalistado.getColumnModel().getColumn(1).setPreferredWidth(0);

        tablalistado.getColumnModel().getColumn(2).setMaxWidth(0);
        tablalistado.getColumnModel().getColumn(2).setMinWidth(0);
        tablalistado.getColumnModel().getColumn(2).setPreferredWidth(0);

        tablalistado.getColumnModel().getColumn(4).setMaxWidth(0);
        tablalistado.getColumnModel().getColumn(4).setMinWidth(0);
        tablalistado.getColumnModel().getColumn(4).setPreferredWidth(0);

        tablalistado.getColumnModel().getColumn(6).setMaxWidth(0);
        tablalistado.getColumnModel().getColumn(6).setMinWidth(0);
        tablalistado.getColumnModel().getColumn(6).setPreferredWidth(0);

    }

    void inhabilitar() {

        pnlregistro.setVisible(false);
        txtidkpi.setVisible(false);
        txtidpersona.setVisible(false);
        txtidresultados.setVisible(false);

        btneliminar.setEnabled(false);
        btneditar1.setEnabled(false);

        txttrabajador.setEnabled(false);
        txtkpi.setEnabled(false);

        txtidpersona.setText("");
        txtidresultados.setText("");
        txtidkpi.setText("");

        txtresultado.setText("");

        txtkpi.setText("");
        txttrabajador.setText("");

    }

    void habilitar() {

        txtidkpi.setVisible(false);
        txtidpersona.setVisible(false);
        txtidresultados.setVisible(false);
        pnlregistro.setVisible(true);

        txtidpersona.setText("");
        txtidresultados.setText("");
        txtidkpi.setText("");

        txtresultado.setText("");

        txtkpi.setText("");
        txttrabajador.setText("");
    }

    void habilitar_btnpr() {
        btneliminar.setEnabled(true);
        btneditar1.setEnabled(true);
    }

    void mostrar(String buscar, String filtrores) {
        try {
            DefaultTableModel modelo;
            fresultados func = new fresultados();
            modelo = func.mostrar(buscar, filtrores);
            tablalistado.setModel(modelo);
            ocultar_columnas();

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        pnllistado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablalistado = new javax.swing.JTable();
        txtbuscar = new javax.swing.JTextField();
        btneliminar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btneditar1 = new javax.swing.JButton();
        cbofiltro = new javax.swing.JComboBox<>();
        lblfiltrar = new javax.swing.JLabel();
        btneliminarbulk = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        pnlregistro = new javax.swing.JPanel();
        txtidpersona = new javax.swing.JTextField();
        txtidresultados = new javax.swing.JTextField();
        txtidkpi = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lblnombrekpi6 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        lblnombrekpi7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txttrabajador = new javax.swing.JTextField();
        btnbuscartrabajador = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtkpi = new javax.swing.JTextField();
        btnbuscarkpi = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        txtresultado = new javax.swing.JTextField();
        btnupdownload = new javax.swing.JButton();
        lblnombrekpi13 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblnombrearea1 = new javax.swing.JLabel();
        datemes = new com.toedter.calendar.JMonthChooser();
        dateyear = new com.toedter.calendar.JYearChooser();
        jPanel6 = new javax.swing.JPanel();
        btnanalisis7 = new javax.swing.JButton();
        btnanalisis5 = new javax.swing.JButton();
        btnproyeccion = new javax.swing.JButton();
        btnevolutivo = new javax.swing.JButton();
        btncomparacion = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Resultados");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(75, 16, 160));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Resultados");
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(79, 20));
        jPanel1.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1181, 511));

        jPanel7.setPreferredSize(new java.awt.Dimension(920, 500));
        jPanel7.setLayout(new java.awt.BorderLayout());

        pnllistado.setBackground(new java.awt.Color(101, 54, 193));

        jScrollPane1.setBackground(new java.awt.Color(102, 50, 159));

        tablalistado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tablalistado.setForeground(new java.awt.Color(75, 16, 160));
        tablalistado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablalistado.setGridColor(new java.awt.Color(75, 16, 160));
        tablalistado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablalistadoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablalistadoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablalistado);

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(153, 51, 0));
        btneliminar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        btneliminar.setToolTipText("Eliminar seleccionado");
        btneliminar.setBorder(null);
        btneliminar.setBorderPainted(false);
        btneliminar.setContentAreaFilled(false);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnnuevo.setBackground(new java.awt.Color(0, 51, 0));
        btnnuevo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnnuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        btnnuevo.setToolTipText("Crear nuevo");
        btnnuevo.setBorder(null);
        btnnuevo.setBorderPainted(false);
        btnnuevo.setContentAreaFilled(false);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btneditar1.setBackground(new java.awt.Color(0, 51, 0));
        btneditar1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btneditar1.setForeground(new java.awt.Color(255, 255, 255));
        btneditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btneditar1.setToolTipText("Editar seleccionado");
        btneditar1.setBorder(null);
        btneditar1.setBorderPainted(false);
        btneditar1.setContentAreaFilled(false);
        btneditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditar1ActionPerformed(evt);
            }
        });

        cbofiltro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbofiltro.setForeground(new java.awt.Color(75, 16, 160));
        cbofiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Documento", "Nombre", "1erApellido", "Area", "SubArea", "KPI", "Año", "Mes", "Resultado" }));
        cbofiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbofiltroItemStateChanged(evt);
            }
        });

        lblfiltrar.setForeground(new java.awt.Color(255, 255, 255));
        lblfiltrar.setText("Filtrar por:");

        btneliminarbulk.setBackground(new java.awt.Color(153, 51, 0));
        btneliminarbulk.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btneliminarbulk.setForeground(new java.awt.Color(255, 255, 255));
        btneliminarbulk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminarmultiples.png"))); // NOI18N
        btneliminarbulk.setToolTipText("Eliminar Multiples Filas de la Tabla entre fechas seleccionadas");
        btneliminarbulk.setBorder(null);
        btneliminarbulk.setBorderPainted(false);
        btneliminarbulk.setContentAreaFilled(false);
        btneliminarbulk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarbulkActionPerformed(evt);
            }
        });

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnbuscar.setBorder(null);
        btnbuscar.setBorderPainted(false);
        btnbuscar.setContentAreaFilled(false);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnllistadoLayout = new javax.swing.GroupLayout(pnllistado);
        pnllistado.setLayout(pnllistadoLayout);
        pnllistadoLayout.setHorizontalGroup(
            pnllistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnllistadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnllistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                    .addGroup(pnllistadoLayout.createSequentialGroup()
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscar)
                        .addGap(18, 18, 18)
                        .addComponent(lblfiltrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbofiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnllistadoLayout.createSequentialGroup()
                        .addComponent(btneliminarbulk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneditar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnllistadoLayout.setVerticalGroup(
            pnllistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnllistadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnllistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnllistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbofiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblfiltrar))
                    .addComponent(btnbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addGroup(pnllistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnllistadoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnllistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btneditar1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnllistadoLayout.createSequentialGroup()
                                .addComponent(btneliminar)
                                .addContainerGap())))
                    .addGroup(pnllistadoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btneliminarbulk))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnllistadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnnuevo)
                .addContainerGap())
        );

        pnllistadoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btneliminar, btnnuevo});

        jPanel7.add(pnllistado, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel7);

        pnlregistro.setBackground(new java.awt.Color(255, 255, 255));
        pnlregistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 54, 193)));
        pnlregistro.setPreferredSize(new java.awt.Dimension(267, 300));

        jPanel5.setOpaque(false);

        lblnombrekpi6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblnombrekpi6.setForeground(new java.awt.Color(75, 16, 160));
        lblnombrekpi6.setText("Trabajador:");

        btnguardar.setBackground(new java.awt.Color(0, 51, 0));
        btnguardar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnguardar.setToolTipText("Aceptar y guardar");
        btnguardar.setBorder(null);
        btnguardar.setBorderPainted(false);
        btnguardar.setContentAreaFilled(false);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        lblnombrekpi7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblnombrekpi7.setForeground(new java.awt.Color(75, 16, 160));
        lblnombrekpi7.setText("Resultado:");

        jPanel2.setBackground(new java.awt.Color(153, 103, 198));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        txttrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttrabajadorActionPerformed(evt);
            }
        });
        jPanel2.add(txttrabajador);

        btnbuscartrabajador.setBackground(new java.awt.Color(0, 51, 0));
        btnbuscartrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscarlista.png"))); // NOI18N
        btnbuscartrabajador.setToolTipText("Buscar trabajador");
        btnbuscartrabajador.setBorder(null);
        btnbuscartrabajador.setBorderPainted(false);
        btnbuscartrabajador.setContentAreaFilled(false);
        btnbuscartrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscartrabajadorActionPerformed(evt);
            }
        });
        jPanel2.add(btnbuscartrabajador);

        jPanel3.setBackground(new java.awt.Color(153, 103, 198));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        txtkpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkpiActionPerformed(evt);
            }
        });
        jPanel3.add(txtkpi);

        btnbuscarkpi.setBackground(new java.awt.Color(0, 51, 0));
        btnbuscarkpi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscarlista.png"))); // NOI18N
        btnbuscarkpi.setToolTipText("Buscar KPI");
        btnbuscarkpi.setBorder(null);
        btnbuscarkpi.setBorderPainted(false);
        btnbuscarkpi.setContentAreaFilled(false);
        btnbuscarkpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarkpiActionPerformed(evt);
            }
        });
        jPanel3.add(btnbuscarkpi);

        btncancelar.setBackground(new java.awt.Color(0, 51, 0));
        btncancelar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btncancelar.setToolTipText("Cancelar");
        btncancelar.setBorder(null);
        btncancelar.setBorderPainted(false);
        btncancelar.setContentAreaFilled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        txtresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresultadoActionPerformed(evt);
            }
        });
        txtresultado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtresultadoKeyTyped(evt);
            }
        });

        btnupdownload.setBackground(new java.awt.Color(255, 255, 255));
        btnupdownload.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnupdownload.setForeground(new java.awt.Color(75, 16, 160));
        btnupdownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/upandown.png"))); // NOI18N
        btnupdownload.setText("Cargar ");
        btnupdownload.setToolTipText("Subir datos o descargar plantilla");
        btnupdownload.setBorder(null);
        btnupdownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdownloadActionPerformed(evt);
            }
        });

        lblnombrekpi13.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblnombrekpi13.setForeground(new java.awt.Color(75, 16, 160));
        lblnombrekpi13.setText("KPI:");

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        lblnombrearea1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblnombrearea1.setForeground(new java.awt.Color(75, 16, 160));
        lblnombrearea1.setText("Fecha:");
        lblnombrearea1.setMinimumSize(new java.awt.Dimension(32, 10));
        lblnombrearea1.setPreferredSize(new java.awt.Dimension(50, 10));
        jPanel10.add(lblnombrearea1);

        datemes.setOpaque(false);
        jPanel10.add(datemes);

        dateyear.setPreferredSize(new java.awt.Dimension(58, 20));
        jPanel10.add(dateyear);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnupdownload, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnguardar))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnombrekpi6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblnombrekpi13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblnombrekpi7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel2, jPanel3});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblnombrekpi6)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblnombrekpi13))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombrekpi7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnguardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdownload, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(111, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlregistroLayout = new javax.swing.GroupLayout(pnlregistro);
        pnlregistro.setLayout(pnlregistroLayout);
        pnlregistroLayout.setHorizontalGroup(
            pnlregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlregistroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtidpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtidkpi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidresultados, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(pnlregistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlregistroLayout.setVerticalGroup(
            pnlregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlregistroLayout.createSequentialGroup()
                .addGroup(pnlregistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidpersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidresultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidkpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(pnlregistro);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnanalisis7.setBackground(new java.awt.Color(255, 255, 255));
        btnanalisis7.setFont(new java.awt.Font("abeatbyKai", 0, 18)); // NOI18N
        btnanalisis7.setForeground(new java.awt.Color(75, 16, 160));
        btnanalisis7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/obtenido_persona.png"))); // NOI18N
        btnanalisis7.setText("Obtenido por Persona");
        btnanalisis7.setToolTipText("Estímulo obtenido por persona");
        btnanalisis7.setBorder(null);
        btnanalisis7.setBorderPainted(false);
        btnanalisis7.setContentAreaFilled(false);
        btnanalisis7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanalisis7ActionPerformed(evt);
            }
        });
        jPanel6.add(btnanalisis7);

        btnanalisis5.setBackground(new java.awt.Color(255, 255, 255));
        btnanalisis5.setFont(new java.awt.Font("abeatbyKai", 0, 18)); // NOI18N
        btnanalisis5.setForeground(new java.awt.Color(75, 16, 160));
        btnanalisis5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/todo.png"))); // NOI18N
        btnanalisis5.setText("Analisis de Resultados");
        btnanalisis5.setToolTipText("Análisis histórico de todos los resultados");
        btnanalisis5.setBorder(null);
        btnanalisis5.setBorderPainted(false);
        btnanalisis5.setContentAreaFilled(false);
        btnanalisis5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanalisis5ActionPerformed(evt);
            }
        });
        jPanel6.add(btnanalisis5);

        btnproyeccion.setBackground(new java.awt.Color(255, 255, 255));
        btnproyeccion.setFont(new java.awt.Font("abeatbyKai", 0, 18)); // NOI18N
        btnproyeccion.setForeground(new java.awt.Color(75, 16, 160));
        btnproyeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analisis.png"))); // NOI18N
        btnproyeccion.setText("Mi Stymuli Proyectado");
        btnproyeccion.setToolTipText("Gráfica proyección estímulo obtenido frente a estímulo posible");
        btnproyeccion.setBorder(null);
        btnproyeccion.setBorderPainted(false);
        btnproyeccion.setContentAreaFilled(false);
        btnproyeccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnproyeccion.setPreferredSize(new java.awt.Dimension(250, 54));
        btnproyeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproyeccionActionPerformed(evt);
            }
        });
        jPanel6.add(btnproyeccion);

        btnevolutivo.setBackground(new java.awt.Color(255, 255, 255));
        btnevolutivo.setFont(new java.awt.Font("abeatbyKai", 0, 18)); // NOI18N
        btnevolutivo.setForeground(new java.awt.Color(75, 16, 160));
        btnevolutivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analisis.png"))); // NOI18N
        btnevolutivo.setText("Mi Evolutivo de KPI");
        btnevolutivo.setToolTipText("Gráfica evolutivo mensual");
        btnevolutivo.setBorder(null);
        btnevolutivo.setBorderPainted(false);
        btnevolutivo.setContentAreaFilled(false);
        btnevolutivo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnevolutivo.setPreferredSize(new java.awt.Dimension(240, 54));
        btnevolutivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnevolutivoActionPerformed(evt);
            }
        });
        jPanel6.add(btnevolutivo);

        btncomparacion.setBackground(new java.awt.Color(255, 255, 255));
        btncomparacion.setFont(new java.awt.Font("abeatbyKai", 0, 18)); // NOI18N
        btncomparacion.setForeground(new java.awt.Color(75, 16, 160));
        btncomparacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analisis.png"))); // NOI18N
        btncomparacion.setText("Distribucion KPI");
        btncomparacion.setToolTipText("Gráfica comparación KPI, valor objetivo frente a valor obtenido");
        btncomparacion.setBorder(null);
        btncomparacion.setBorderPainted(false);
        btncomparacion.setContentAreaFilled(false);
        btncomparacion.setFocusPainted(false);
        btncomparacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btncomparacion.setPreferredSize(new java.awt.Dimension(195, 54));
        btncomparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomparacionActionPerformed(evt);
            }
        });
        jPanel6.add(btncomparacion);

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablalistadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablalistadoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tablalistadoMouseClicked

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        int fila = tablalistado.getSelectedRow();

        txtidresultados.setText(tablalistado.getValueAt(fila, 0).toString());
        if (!txtidresultados.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Esta seguro de eliminar el Resultado", "Confirmar", 2);

            if (confirmacion == 0) {
                vresultados dts = new vresultados();
                fresultados func = new fresultados();

                dts.setIdresultados(Integer.parseInt(txtidresultados.getText()));
                func.eliminar(dts);
                mostrar("", filtropor);
                inhabilitar();

            }

        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed

        habilitar();

        btnguardar.setIcon(new ImageIcon(frmresultados.class.getResource("/img/guardar.png")));
        accion = "guardar";


    }//GEN-LAST:event_btnnuevoActionPerformed

    private void tablalistadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablalistadoMousePressed
        habilitar_btnpr();
        // TODO add your handling code here:
    }//GEN-LAST:event_tablalistadoMousePressed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void txtkpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkpiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkpiActionPerformed

    private void btnbuscarkpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarkpiActionPerformed

        if (txtidpersona.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una Persona primero");
            txtidpersona.requestFocus();
            return;

        }
        con.loadingscreen();
        SwingWorker swingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                conexion.formsubarea = frmresultados.txtidpersona.getText();

                frmvistakpi form = new frmvistakpi();
                form.toFront();
                form.setVisible(true);
                form.setAlwaysOnTop(true);
                form.setLocationRelativeTo(btnbuscarkpi);
                con.hideloading();
                return null;
            }
        };
        swingWorker.execute();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarkpiActionPerformed

    private void btnbuscartrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscartrabajadorActionPerformed

        con.loadingscreen();
        SwingWorker swingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {        // TODO add your handling code here:
                txtkpi.setText("");
                txtidkpi.setText("");
                frmvistatrabajador form = new frmvistatrabajador();
                form.toFront();
                form.setVisible(true);
                form.setAlwaysOnTop(true);
                form.setLocationRelativeTo(btnbuscartrabajador);
                con.hideloading();
                return null;
            }
        };
        swingWorker.execute();

    }//GEN-LAST:event_btnbuscartrabajadorActionPerformed

    private void txtresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresultadoActionPerformed
        // TODO add your handling code here:
        txtresultado.transferFocus();
    }//GEN-LAST:event_txtresultadoActionPerformed

    private void txttrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttrabajadorActionPerformed
        // TODO add your handling code here:

        txttrabajador.transferFocus();
    }//GEN-LAST:event_txttrabajadorActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        inhabilitar();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:

        if (txtidpersona.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Trabajador");
            txtidpersona.requestFocus();
            return;

        }
        if (txtidkpi.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un KPI");
            txtidkpi.requestFocus();
            return;

        }

        if (txtresultado.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el Resultado del KPI");
            txtresultado.requestFocus();
            return;

        }

        vresultados dts = new vresultados();
        fresultados func = new fresultados();

        dts.setIdkpi(Integer.parseInt(txtidkpi.getText()));
        dts.setIdpersona(Integer.parseInt(txtidpersona.getText()));
        dts.setResultado_kpi(con.DBnumberFormatInput(txtresultado.getText()));

        int mes = datemes.getMonth() + 1;
        String messtring = "";

        switch (mes) {
            case 1:
                messtring = "01_Enero";
                break;
            case 2:
                messtring = "02_Febrero";
                break;
            case 3:
                messtring = "03_Marzo";
                break;
            case 4:
                messtring = "04_Abril";
                break;
            case 5:
                messtring = "05_Mayo";
                break;
            case 6:
                messtring = "06_Junio";
                break;
            case 7:
                messtring = "07_Julio";
                break;
            case 8:
                messtring = "08_Agosto";
                break;
            case 9:
                messtring = "09_Septiembre";
                break;
            case 10:
                messtring = "10_Octubre";
                break;
            case 11:
                messtring = "11_Noviembre";
                break;
            case 12:
                messtring = "12_Diciembre";
                break;

        }

        dts.setMes(messtring);
        dts.setYear(dateyear.getYear());

        if (accion.equals("guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "El Resultado fue registrado satisfactoriamente");
                mostrar("", filtropor);
                inhabilitar();

            }

        } else if (accion.equals("editar")) {
            dts.setIdresultados(Integer.parseInt(txtidresultados.getText()));
            if (func.editar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "El Resultado fue editado satisfactoriamente");
                mostrar("", filtropor);
                inhabilitar();

            }

        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditar1ActionPerformed
        btnguardar.setIcon(new ImageIcon(frmresultados.class.getResource("/img/editar.png")));
        habilitar();
        btneliminar.setEnabled(true);
        accion = "editar";

        int fila = tablalistado.getSelectedRow();

        txtidresultados.setText(tablalistado.getValueAt(fila, 0).toString());
        txtidkpi.setText(tablalistado.getValueAt(fila, 1).toString());
        txtidpersona.setText(tablalistado.getValueAt(fila, 2).toString());
        txttrabajador.setText(tablalistado.getValueAt(fila, 3).toString());
        txtkpi.setText(tablalistado.getValueAt(fila, 8).toString());
        txtresultado.setText(tablalistado.getValueAt(fila, 9).toString());

        String years = tablalistado.getValueAt(fila, 11).toString();
        String messcompleto = tablalistado.getValueAt(fila, 10).toString();
        String mess = messcompleto.substring(0, 2);
        int mes = Integer.parseInt(mess) - 1;
        int year = Integer.parseInt(years);
        datemes.setMonth(mes);
        dateyear.setYear(year);


    }//GEN-LAST:event_btneditar1ActionPerformed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void txtresultadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtresultadoKeyTyped

    }//GEN-LAST:event_txtresultadoKeyTyped

    private void btnupdownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdownloadActionPerformed

        this.dispose();
        frmupdownresultados form = new frmupdownresultados();
        form.toFront();
        form.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnupdownloadActionPerformed

    private void cbofiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbofiltroItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbofiltroItemStateChanged

    private void btnanalisis7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanalisis7ActionPerformed
        con.loadingscreen();
        SwingWorker swingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {

                INICIO.pnlmain.removeAll();
                INICIO.pnlmain.revalidate();
                INICIO.pnlmain.repaint();

                frmanalisisobtpersona formobtpe = new frmanalisisobtpersona();

                if (INICIO.lblinicioacceso.getText().equals("Jefe de Area")) {

                    frmanalisisobtpersona.pnlarea.setVisible(false);
                    frmanalisisobtpersona.txtnombrearea.setText(INICIO.lblinicioarea.getText());

                } else if (INICIO.lblinicioacceso.getText().equals("Jefe de Subarea")) {

                    frmanalisisobtpersona.pnlarea.setVisible(false);
                    frmanalisisobtpersona.txtnombrearea.setText(INICIO.lblinicioarea.getText());

                }
                INICIO.pnlmain.add(formobtpe);
                formobtpe.toFront();
                formobtpe.setVisible(true);
                formobtpe.setSize(INICIO.pnlmain.getSize());
                con.hideloading();
                return null;
            }
        };
        swingWorker.execute();
    }//GEN-LAST:event_btnanalisis7ActionPerformed

    private void btnanalisis5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanalisis5ActionPerformed
        con.loadingscreen();
        SwingWorker swingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                INICIO.pnlmain.removeAll();
                INICIO.pnlmain.revalidate();
                INICIO.pnlmain.repaint();
                frmanalisiscompleto formcompchart = new frmanalisiscompleto();

                if (INICIO.lblinicioacceso.getText().equals("Jefe de Area")) {
                    frmanalisiscompleto.pnlarea.setVisible(false);
                    frmanalisiscompleto.txtnombrearea.setText(INICIO.lblinicioarea.getText());

                } else if (INICIO.lblinicioacceso.getText().equals("Jefe de Subarea")) {
                    frmanalisiscompleto.pnlarea.setVisible(false);
                    frmanalisiscompleto.txtnombrearea.setText(INICIO.lblinicioarea.getText());
                }
                INICIO.pnlmain.add(formcompchart);
                formcompchart.toFront();
                formcompchart.setVisible(true);
                formcompchart.setSize(INICIO.pnlmain.getSize());
                con.hideloading();
                return null;
            }
        };
        swingWorker.execute();
    }//GEN-LAST:event_btnanalisis5ActionPerformed

    private void btnproyeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproyeccionActionPerformed
        con.loadingscreen();
        SwingWorker swingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                INICIO.pnlmain.removeAll();
                INICIO.pnlmain.revalidate();
                INICIO.pnlmain.repaint();

                frmanalisproyeccion form5chart = new frmanalisproyeccion();

                if (INICIO.lblinicioacceso.getText().equals("Trabajador")) {

                    frmanalisproyeccion.pnlarea.setVisible(false);
                    frmanalisproyeccion.txtnombrearea.setText(INICIO.lblinicioarea.getText());
                    frmanalisproyeccion.pnlsubarea.setVisible(false);
                    frmanalisproyeccion.txtnombresubarea.setText(INICIO.lbliniciosubarea.getText());
                    frmanalisproyeccion.pnltrabajador.setVisible(false);
                    frmanalisproyeccion.txtpersonadocumento.setText(INICIO.lbliniciodocumento.getText());
                    frmanalisproyeccion.jPanel2.setVisible(false);
                    frmanalisproyeccion.jPanel10.setBackground(Color.WHITE);
                }
                INICIO.pnlmain.add(form5chart);
                form5chart.toFront();
                form5chart.setVisible(true);
                form5chart.setSize(INICIO.pnlmain.getSize());
                con.hideloading();
                return null;
            }
        };
        swingWorker.execute();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnproyeccionActionPerformed

    private void btnevolutivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnevolutivoActionPerformed
        con.loadingscreen();
        SwingWorker swingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                INICIO.pnlmain.removeAll();
                INICIO.pnlmain.revalidate();
                INICIO.pnlmain.repaint();

                frmanalisevolutivo form3chart = new frmanalisevolutivo();

                if (INICIO.lblinicioacceso.getText().equals("Trabajador")) {

                    frmanalisevolutivo.pnlarea.setVisible(false);
                    frmanalisevolutivo.txtnombrearea.setText(INICIO.lblinicioarea.getText());
                    frmanalisevolutivo.pnlsubarea.setVisible(false);
                    frmanalisevolutivo.txtnombresubarea.setText(INICIO.lbliniciosubarea.getText());
                    frmanalisevolutivo.jPanel2.setVisible(false);
                    frmanalisevolutivo.jPanel7.setBackground(Color.WHITE);
                }
                INICIO.pnlmain.add(form3chart);
                form3chart.toFront();
                form3chart.setVisible(true);
                form3chart.setSize(INICIO.pnlmain.getSize());
                con.hideloading();
                return null;
            }
        };
        swingWorker.execute();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnevolutivoActionPerformed

    private void btncomparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomparacionActionPerformed
        con.loadingscreen();
        SwingWorker swingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                INICIO.pnlmain.removeAll();
                INICIO.pnlmain.revalidate();
                INICIO.pnlmain.repaint();

                frmanalisdistrikpi form1chart = new frmanalisdistrikpi();

                if (INICIO.lblinicioacceso.getText().equals("Trabajador")) {
                    frmanalisdistrikpi.pnlarea.setVisible(false);
                    frmanalisdistrikpi.txtnombrearea.setText(INICIO.lblinicioarea.getText());
                    frmanalisdistrikpi.pnlsubarea.setVisible(false);
                    frmanalisdistrikpi.txtnombresubarea.setText(INICIO.lbliniciosubarea.getText());
                    frmanalisdistrikpi.jPanel2.setVisible(false);
                    frmanalisdistrikpi.jPanel9.setBackground(Color.WHITE);
                }
                INICIO.pnlmain.add(form1chart);
                form1chart.toFront();
                form1chart.setVisible(true);
                form1chart.setSize(INICIO.pnlmain.getSize());
                con.hideloading();
                return null;
            }
        };
        swingWorker.execute();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncomparacionActionPerformed

    private void btneliminarbulkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarbulkActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Esta seguro de eliminar Multiples Datos de la Tabla?", "Confirmar", 2, JOptionPane.WARNING_MESSAGE);

        if (confirmacion == 0) {
            INICIO.pnlmain.removeAll();
            INICIO.pnlmain.revalidate();
            INICIO.pnlmain.repaint();
            frmzzdeletebulk forma = new frmzzdeletebulk();
            INICIO.pnlmain.add(forma);
            forma.setVisible(true);
            forma.toFront();
            forma.setSize(INICIO.pnlmain.getSize());
            forma.lbltitulo.setText("Borrar datos de Tabla Resultados entre Fechas");
            fsqloperations.tablaerrasebulk = "resultados";

        }

// TODO add your handling code here:
    }//GEN-LAST:event_btneliminarbulkActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        con.loadingscreen();
        SwingWorker swingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                int seleccionado = cbofiltro.getSelectedIndex();
                if (((String) cbofiltro.getItemAt(seleccionado)).equals("Documento")) {
                    filtropor = "p.documento";
                } else if (((String) cbofiltro.getItemAt(seleccionado)).equals("Nombre")) {
                    filtropor = "p.nombre";
                } else if (((String) cbofiltro.getItemAt(seleccionado)).equals("1erApellido")) {
                    filtropor = "p.apaterno";
                } else if (((String) cbofiltro.getItemAt(seleccionado)).equals("Area")) {
                    filtropor = "a.nombre";
                } else if (((String) cbofiltro.getItemAt(seleccionado)).equals("SubArea")) {
                    filtropor = "s.nombre";
                } else if (((String) cbofiltro.getItemAt(seleccionado)).equals("KPI")) {
                    filtropor = "k.nombre";
                } else if (((String) cbofiltro.getItemAt(seleccionado)).equals("Año")) {
                    filtropor = "r.year";
                } else if (((String) cbofiltro.getItemAt(seleccionado)).equals("Mes")) {
                    filtropor = "r.mes";
                } else if (((String) cbofiltro.getItemAt(seleccionado)).equals("Resultado")) {
                    filtropor = "r.resultado_kpi";
                }

                mostrar(txtbuscar.getText(), filtropor);
                con.hideloading();
                return null;
            }
        };
        swingWorker.execute();
    }//GEN-LAST:event_btnbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmresultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmresultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmresultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmresultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmresultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnanalisis5;
    public static javax.swing.JButton btnanalisis7;
    public static javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnbuscarkpi;
    private javax.swing.JButton btnbuscartrabajador;
    private javax.swing.JButton btncancelar;
    public static javax.swing.JButton btncomparacion;
    public static javax.swing.JButton btneditar1;
    public static javax.swing.JButton btneliminar;
    public static javax.swing.JButton btneliminarbulk;
    public static javax.swing.JButton btnevolutivo;
    private javax.swing.JButton btnguardar;
    public static javax.swing.JButton btnnuevo;
    public static javax.swing.JButton btnproyeccion;
    private javax.swing.JButton btnupdownload;
    public static javax.swing.JComboBox<String> cbofiltro;
    private com.toedter.calendar.JMonthChooser datemes;
    private com.toedter.calendar.JYearChooser dateyear;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblfiltrar;
    public static javax.swing.JLabel lblnombrearea1;
    private javax.swing.JLabel lblnombrekpi13;
    private javax.swing.JLabel lblnombrekpi6;
    private javax.swing.JLabel lblnombrekpi7;
    private javax.swing.JPanel pnllistado;
    private javax.swing.JPanel pnlregistro;
    private javax.swing.JTable tablalistado;
    public static javax.swing.JTextField txtbuscar;
    public static javax.swing.JTextField txtidkpi;
    public static javax.swing.JTextField txtidpersona;
    private static javax.swing.JTextField txtidresultados;
    public static javax.swing.JTextField txtkpi;
    private javax.swing.JTextField txtresultado;
    public static javax.swing.JTextField txttrabajador;
    // End of variables declaration//GEN-END:variables
}
