/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import datos.vtrabajador;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logica.ftrabajador;
import static logica.ftrabajador.dbpasswordexist;

/**
 *
 * @author crist
 */
public class frmzzlogin extends javax.swing.JFrame {

    /**
     * Creates new form frmzzlogin
     */
    public frmzzlogin() {
        initComponents();
        setIcon();
        txtusuario.requestFocus();
        this.setLocationRelativeTo(null);

        rootPane.setDefaultButton(btningresar);

    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtusuario = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btningresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnconfiguration = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(75, 16, 160));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 16, 160)));

        jLabel1.setBackground(new java.awt.Color(75, 16, 160));
        jLabel1.setFont(new java.awt.Font("abeatbyKai", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 16, 160));
        jLabel1.setText("Documento:");

        jLabel2.setBackground(new java.awt.Color(75, 16, 160));
        jLabel2.setFont(new java.awt.Font("abeatbyKai", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(75, 16, 160));
        jLabel2.setText("Password:");

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        btningresar.setBackground(new java.awt.Color(255, 255, 255));
        btningresar.setFont(new java.awt.Font("abeatbyKai", 0, 18)); // NOI18N
        btningresar.setForeground(new java.awt.Color(75, 16, 160));
        btningresar.setText("  Ingresar  ");
        btningresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btningresar.setBorderPainted(false);
        btningresar.setFocusPainted(false);
        btningresar.setFocusable(false);
        btningresar.setMinimumSize(new java.awt.Dimension(106, 30));
        btningresar.setPreferredSize(new java.awt.Dimension(110, 54));
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });
        jPanel3.add(btningresar, new java.awt.GridBagConstraints());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/color-fondo-transparente63x18.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/isotipo-1-fondo-transparente91x77.png"))); // NOI18N

        btnconfiguration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuration.png"))); // NOI18N
        btnconfiguration.setBorder(null);
        btnconfiguration.setBorderPainted(false);
        btnconfiguration.setContentAreaFilled(false);
        btnconfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfigurationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtusuario)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnconfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(107, 107, 107)))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnconfiguration)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("abeatbyKai", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Bienvenido a Stymuli");

        btncancelar.setBackground(new java.awt.Color(0, 51, 0));
        btncancelar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CANCELARCITO.png"))); // NOI18N
        btncancelar.setToolTipText("Cancelar");
        btncancelar.setBorder(null);
        btncancelar.setBorderPainted(false);
        btncancelar.setContentAreaFilled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncancelar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncancelar)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed

        File f = new File("conf\\config.txt");//revisa que el archivo config existe ya
        if (f.exists() && !f.isDirectory()) {

            try {

                ftrabajador func = new ftrabajador();
                vtrabajador dts = new vtrabajador();

                dts.setDocumento(txtusuario.getText());
                dts.setPassword(txtpassword.getText());

                if (func.login(txtusuario.getText(), txtpassword.getText())) {

                    this.dispose();
                    INICIO form = new INICIO();
                    form.toFront();
                    form.setVisible(true);
                    form.setExtendedState(INICIO.MAXIMIZED_BOTH);
                    form.setIconImage(Toolkit.getDefaultToolkit().getImage("/img/editar.png"));

                    if (ftrabajador.loginacceso.equals("Trabajador")) {
                        INICIO.btnareas.setVisible(false);
                        INICIO.btnkpi.setVisible(false);
                        INICIO.btnmodelos.setVisible(false);
                        INICIO.btnusuarios.setVisible(false);
                        INICIO.btnanalisis.setVisible(false);
                        INICIO.btnresultados.setText("Historico");
                        INICIO.menudatabase.setVisible(false);

                    } else if (ftrabajador.loginacceso.equals("Administrador")) {
                        INICIO.btnperfil.setVisible(false);

                    } else if (ftrabajador.loginacceso.equals("Jefe de Area")) {
                        INICIO.btnareas.setVisible(false);
                        INICIO.btnperfil.setVisible(false);
                        INICIO.menudatabase.setVisible(false);

                    } else if (ftrabajador.loginacceso.equals("Jefe de Subarea")) {
                        INICIO.btnareas.setVisible(false);
                        INICIO.btnperfil.setVisible(false);
                        INICIO.menudatabase.setVisible(false);

                    } else {
                        INICIO.btnareas.setVisible(false);
                        INICIO.btnkpi.setVisible(false);
                        INICIO.btnmodelos.setVisible(false);
                        INICIO.btnusuarios.setVisible(false);
                        INICIO.btnperfil.setVisible(false);
                        INICIO.btnresultados.setVisible(false);
                        INICIO.btnsimulac.setVisible(false);
                        INICIO.btnanalisis.setVisible(false);
                        INICIO.menudatabase.setVisible(false);
                        INICIO.menuappconf.setVisible(false);

                        JOptionPane.showMessageDialog(null, "No tiene un perfil válido Asignado, "
                                + "Por favor comuniquese con el administrador");

                    }

                    INICIO.lblinicioidpersona.setText(ftrabajador.loginidpersona);
                    INICIO.lblinicionombre.setText(ftrabajador.loginnombre);
                    INICIO.lblinicio1erapellido.setText(ftrabajador.login1erapellido);
                    INICIO.lblinicio2doapellido.setText(ftrabajador.login2doapellido);
                    INICIO.lbliniciodocumento.setText(txtusuario.getText());
                    INICIO.lblinicioemail.setText(ftrabajador.loginemail);
                    INICIO.lblinicioidarea.setText(ftrabajador.loginidarea);
                    INICIO.lblinicioarea.setText(ftrabajador.loginarea);
                    INICIO.lblinicioidsubarea.setText(ftrabajador.loginidsubarea);
                    INICIO.lbliniciosubarea.setText(ftrabajador.loginsubarea);
                    INICIO.lblinicioacceso.setText(ftrabajador.loginacceso);

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Contraseña incorrecta", "Acceso al Sistema", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                if (dbpasswordexist.equals("existe")) {
                    JOptionPane.showMessageDialog(rootPane, "Primer Acceso al Sistema, cree una nueva contraseña");
                    this.dispose();
                    frmzzcrearpass form = new frmzzcrearpass();
                    form.toFront();
                    form.setVisible(true);
                    form.txtdocumento.setText(txtusuario.getText());

                } else if (dbpasswordexist.equals("na")) {
                    JOptionPane.showMessageDialog(rootPane, "El Usuario no Existe", "Acceso al Sistema", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Acceso Denegado", "Acceso al Sistema", JOptionPane.ERROR_MESSAGE);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe Especificar cual es la base de Datos a Usar");
            btnconfiguration.doClick();
        }//revisa si config existe


    }//GEN-LAST:event_btningresarActionPerformed

    private void btnconfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfigurationActionPerformed
        frmconfiguracion form = new frmconfiguracion();
        form.toFront();
        form.setVisible(true);

        form.btncuenta.setVisible(false);
        form.btninter.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnconfigurationActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setIcon();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmzzlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmzzlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmzzlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmzzlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmzzlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnconfiguration;
    private javax.swing.JButton btningresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
 private void setIcon() {
        if (SystemTray.isSupported()) {
            SystemTray tray = SystemTray.getSystemTray();
            Dimension trayIconSize = tray.getTrayIconSize();
            this.setIconImage(new ImageIcon(getClass().getResource("/img/iconodeapp.png")).getImage().getScaledInstance(trayIconSize.width, trayIconSize.height, Image.SCALE_SMOOTH));
        }
    }


}
